### ISSUE TITLE
Possibility to use single set of external dependency submodules?

### ISSUE THREAD

**Issue by plaes** [alexmoon/nrf-sdc#29]
At least in current main, we have two sets of same submodules:
* `51f8f89612c8330c0116479cfe3a2cb04c390e2b nrf-mpsl-sys/third_party/arm/CMSIS_5 (5.9.0-dev-172-g51f8f8961)`
* `075e9e711383bb3babfae4249fd59c8c8d882f72 nrf-mpsl-sys/third_party/nordic/nrfx (v3.6.0)`
* `37e2ac22b6a6d9d9a62c95e8dc2c102d4371c62e nrf-mpsl-sys/third_party/nordic/nrfxlib (v2.7.0)`
* `51f8f89612c8330c0116479cfe3a2cb04c390e2b nrf-sdc-sys/third_party/arm/CMSIS_5 (5.9.0-dev-172-g51f8f8961)`
* `075e9e711383bb3babfae4249fd59c8c8d882f72 nrf-sdc-sys/third_party/nordic/nrfx (v3.6.0)`
* `37e2ac22b6a6d9d9a62c95e8dc2c102d4371c62e nrf-sdc-sys/third_party/nordic/nrfxlib (v2.7.0)`

Would it be feasible to use single set?

**Comment by alexmoon** [comment]
As I recall, the issue is that `cargo publish` wants all inputs to the build to be under the directory of the package. We want to be able to publish these packages on crates.io eventually, so that is important. If there is a way to use a common third_party directory and use it from both packages, that would be great.

**Comment by plaes** [comment]
Let's close for now as this is something that depends on unimplemented feature from Cargo.

**Comment by hkjolhede** [comment]
Jumping in here because I am interested in creating a crate for gzll, which I think would fit well under this project, and it would be unwieldy to have triple copies of the submodules. What about symlinking to a root submodule directory? I have tried it locally and it builds fine. As far as I can tell from the Rust forums, it should work well with cargo publish.
